version: '3'
services:
  backend:
    build: ./backend
    depends_on:
      - "db"
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=useradmin
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=test_app
    command: mysqld --character-set-server=utf8mb4
  nginx:
    build: ./nginx
    depends_on:
      - "backend"
    ports:
      - "8080:8080"
